### ISSUE TITLE
replies

### ISSUE THREAD

**Issue by logizta** [mitchmoser/DonaldTrump#2]
do you think you could make it so it only replies when the person tweets and not when a person replies to someone elses tweet

**Comment by mitchmoser** [comment]
Yes that would be possible.
I don't intend to implement the functionality and this is not an *issue* per se.

Please familiarize yourself with the [Twitter API](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) - specifically the Tweet object - and consider using any of the following attributes:
```
in_reply_to_status_id
in_reply_to_status_id_str
in_reply_to_user_id
in_reply_to_user_id_str
in_reply_to_screen_name
```

These will be `Null` if the tweet is not a reply.
You can test if a attribute is empty by using a simple check:
```
if attribute is None:
    proceed with logic
```
